version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-v1-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
  wrk:
    image: williamyeh/wrk
    container_name: wrk-container
    volumes:
      - ./result:/result
    entrypoint: /bin/sh
    command: "-c '/usr/local/bin/wrk -t10 -c600 -d5s --latency http://fastapi:8000 > /result/result.txt 2>&1'"

    depends_on:
      - fastapi
    # command: ""
    # entrypoint: [ "/bin/bash" ]
