version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-v2-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

  wrk:
    image: williamyeh/wrk
    container_name: wrk-container
    volumes:
      - ./result:/result
    entrypoint: /bin/sh
    command: "-c 'sleep 10 && /usr/local/bin/wrk -t10 -c600 -d30s --latency http://fastapi:8000/sync > /result/sync.txt 2>&1'"
    depends_on:
      - fastapi
    restart: "no"
